"""`judge_desires`, one case per file, held to a snapshot of the whole store it leaves.

A case in `judge_desires/` is the world as an agent finds it — the topology, the levers, the
desire with its met-test, what the instruments read now, what is foreseen and from when, and
whatever stands — loaded into a bare store. The function judges every desire at the present
and at every foreseen instant and writes the judgments; `<case>.snapshot.trig` beside the
case is the whole store afterwards, in the case's own order, so `diff` of case against
snapshot is exactly what judging did. The machinery is the conftest's: compared structurally,
regenerated by `--update-snapshots`, and a case without a snapshot fails rather than passing
on nothing. See knowledge/decisions/judge-desires-then-derive-wants.md.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from orexis_agent_progression import clock

from orexis_agent_deliberation.judge_desires import judge_desires

CASES_DIR = Path(__file__).parent / "judge_desires"
CASES = sorted(p for p in CASES_DIR.glob("*.trig") if "." not in p.stem)


@pytest.mark.parametrize("case", CASES, ids=[c.stem for c in CASES])
def test_judge_desires_leaves_the_store_as_the_snapshot_says(case, monkeypatch, request, snapshots):
    monkeypatch.setattr(clock, "now", lambda: snapshots.NOW)
    agent = snapshots.stand_in(case)
    before = snapshots.snapshot_of(agent.beliefs)
    judge_desires(agent)
    snapshots.held_to(case, request, "judge_desires", before, snapshots.snapshot_of(agent.beliefs))


def test_every_case_is_read_and_no_snapshot_is_orphaned(snapshots):
    """A glob that stopped matching would pass every case by running none."""
    assert len(CASES) >= 11, [c.name for c in CASES]
    assert not snapshots.orphans_in(CASES_DIR)
