"""`derive_wants`, one case per file, held to a snapshot of the whole store it leaves.

A case in `derive_wants/` is the world as an agent finds it — the topology, the desire with its
met-test, what the instruments read now, what is foreseen and from when, the scopes its levers
make, and whatever already stands — loaded into a bare store. `derive_wants` judges every
desire at the present and at every foreseen instant, writes the judgments, and mints the wants
those judgments imply; `<case>.snapshot.trig` beside the case is the whole store afterwards, in
the case's own order, so `diff` of case against snapshot is exactly what it did.

ONE CONTRACT AND ONE SET OF CASES. It was two of each — a world to judge, then the judged state
to derive from — and no caller ever took one half without the other. The judgment graph is
still written and still read on its own (`judgments.witnesses_of`); what went is the seam a
caller could stop at. The machinery is the conftest's: compared structurally, regenerated by
`--update-snapshots`, and a case without a snapshot fails rather than passing on nothing.
See knowledge/decisions/judge-desires-then-derive-wants.md.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from orexis_agent_progression import clock

from orexis_agent_deliberation.derive_wants import derive_wants

CASES_DIR = Path(__file__).parent / "derive_wants"
CASES = sorted(p for p in CASES_DIR.glob("*.trig") if "." not in p.stem)


@pytest.mark.parametrize("case", CASES, ids=[c.stem for c in CASES])
def test_derive_wants_leaves_the_store_as_the_snapshot_says(case, monkeypatch, request, snapshots):
    monkeypatch.setattr(clock, "now", lambda: snapshots.NOW)
    agent = snapshots.stand_in(case)
    before = snapshots.snapshot_of(agent.beliefs)
    derive_wants(agent.beliefs.engine)
    snapshots.held_to(case, request, "derive_wants", before, snapshots.snapshot_of(agent.beliefs))


def test_every_case_is_read_and_no_snapshot_is_orphaned(snapshots):
    """A glob that stopped matching would pass every case by running none."""
    assert len(CASES) >= 13, [c.name for c in CASES]
    assert not snapshots.orphans_in(CASES_DIR)
