"""`derive_wants`, one case per file, held to a PATCH of the store it leaves.

A case in `derive_wants/` is the world as an agent finds it — the topology, the desire with its
met-test, what the instruments read now, what is foreseen and from when, the scopes its levers
make, and whatever already stands — loaded into a bare store. The function judges every desire
at the present and, where it reads met there, at every instant a prediction reaches, and mints
a want for each cluster of what the met-tests read unmet; `<case>.diff` beside the
case is the whole store afterwards, in the case's own order, so `diff` of case against snapshot
is exactly what it did.

THE GROUNDS ARE LAID FIRST, IN THE CASE'S OWN STORE, AND EVERY DESIRE WEIGHED IN EVERY GROUND,
as the Planner sequences them: an act calls no other act, so the derivation reads the weighings
and this harness writes them, with `unweighed` saying which — the same read the Planner asks.
A case is held to a pass as a pass stands: `lay_ground`, `weigh`, the derivation, `withdraw`.
Laid in place rather than into a second store, because a case that declares a ledger declares
it where the withdrawal reads it. The grounds show in the diff, under `ground:`, and so do the
WEIGHINGS of every desire in every ground — the met-test's rows, which are what the wants are
minted from — and every prediction's retraction: a prediction is a diff, and a prediction of a reading that did
not retract the reading it supersedes would leave both standing in the ground.

WHAT A CASE IS HELD TO IS A PASS — `derive_wants` and then `withdraw` against
its answer — because that is the unit a store is left by. The two are separate functions on
purpose (deriving what is wanted and taking away what is not are different decisions), and
`a_filled_tank_withdraws_its_want` is the case that tells them apart: it is the one that fails
if the withdrawal is left out. `a_tank_low_now_refilled_later` is the one that fails if the
derivation reads the state beside the prediction instead of the ground.

NOTHING STANDS BETWEEN A DESIRE AND A WANT, so there is one contract and one set of cases. It
was two of each, with a judgment written between them and a case set per half;
what a met-test reads is a witness now, computed and stored nowhere, and everything the
judgment carried the want carries. The machinery is the conftest's: compared structurally,
regenerated by `--update-snapshots`, and a case without a snapshot fails rather than passing on
nothing. See knowledge/decisions/judge-desires-then-derive-wants.md.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from agent import clock

from agent.planning.derive_wants import derive_wants
from agent.planning.lay_ground import lay_ground
from agent.planning.unweighed import unweighed
from agent.planning.weigh import weigh
from agent.execution.executor import Executor
from agent.planning.withdraw import withdraw

CASES_DIR = Path(__file__).parent / "derive_wants"
CASES = sorted(p for p in CASES_DIR.glob("*.trig") if "." not in p.stem)


@pytest.mark.parametrize("case", CASES, ids=[c.stem for c in CASES])
def test_derive_wants_leaves_the_store_as_the_snapshot_says(case, monkeypatch, request, snapshots):
    monkeypatch.setattr(clock, "now", lambda: snapshots.NOW)
    store = snapshots.stand_in(case)
    lay_ground(store, snapshots.NOW)
    for pair in unweighed(store):
        weigh(store, pair["for"], pair["about"])
    #  WHAT IS WALKED, as the Planner hands it: to the derivation, each walking want with the instant its
    #  step in flight lands — NOW, since no case puts a step in flight — and to the withdrawal.
    walking = set(Executor(store, snapshots.AGENT, intentions=store).walking())
    withdraw(store, derive_wants(store, snapshots.NOW, {w: snapshots.NOW for w in walking}) | walking, snapshots.NOW)
    snapshots.held_to_diff(case, request, "derive_wants", snapshots.snapshot_of(store))


def test_every_case_is_read_and_no_snapshot_is_orphaned(snapshots):
    """A glob that stopped matching would pass every case by running none."""
    assert len(CASES) >= 14, [c.name for c in CASES]
    assert not snapshots.orphans_in(CASES_DIR)


#  EVERY WANT, THE GRAPH IT LIVES IN, WHEN THAT GRAPH'S STRETCH BEGINS AND WHAT THE WANT REOPENS.
_HOMES_Q = """
SELECT ?w ?g ?start ?reopens WHERE {
  GRAPH ?g { ?w a planning:Want . OPTIONAL { ?w planning:reopens ?reopens } }
  GRAPH ?cat { ?cat a orexis:CatalogueGraph . ?g a planning:WantGraph .
               OPTIONAL { ?g dcterms:temporal/orexis:start ?start } } }"""


@pytest.mark.parametrize("reopened", [False, True], ids=["walking", "reopened"])
def test_a_walking_want_a_belief_reopened_is_minted_again_where_its_step_in_flight_lands(monkeypatch, snapshots, reopened):
    """THE SECOND TRIGGER OF SOFT COMMITMENT, THE DERIVATION'S HALF (#921). `a_standing_want_is_left_alone`
    with tank1's want WALKING and its step in flight landing half a minute on. Handed to the derivation as
    a want a belief has reopened, it is taken out of the graph of the stretch it was minted over — which
    held it alone, and goes — and minted again under its own name over a stretch from that landing,
    saying it `planning:reopens` itself, which is the row the Planner holds the plan its search finds to
    the walking intention's untaken steps by. Handed as walking alone, it stands where it was, reopening
    nothing: the case's own snapshot says so of the store."""
    from agent.store import rows
    from datetime import datetime, timedelta
    monkeypatch.setattr(clock, "now", lambda: snapshots.NOW)
    store = snapshots.stand_in(CASES_DIR / "a_standing_want_is_left_alone.trig")
    lay_ground(store, snapshots.NOW)
    for pair in unweighed(store):
        weigh(store, pair["for"], pair["about"])
    want, lands = "http://example.org/test#keeper.in_range.pursued.tank1.level", snapshots.NOW + timedelta(seconds=30)
    before = {r["w"]: r["g"] for r in rows(store, _HOMES_Q, ())}
    wanted = derive_wants(store, snapshots.NOW, {want: lands}, {want} if reopened else set())
    homes = [(r["w"], r["g"], r.get("start"), r.get("reopens")) for r in rows(store, _HOMES_Q, ()) if r["w"] == want]
    assert want in wanted and len(homes) == 1, homes
    ((_, graph, start, reopens),) = homes
    if not reopened:
        assert (graph, reopens) == (before[want], None), "a walking want nothing reopened stands where it was"
        return
    assert (datetime.fromisoformat(start), reopens) == (lands, want), f"minted again where its step in flight lands, reopening itself: {homes}"
    assert graph != before[want] and not rows(store, "SELECT ?s WHERE { GRAPH $g { ?s ?p ?o } } LIMIT 1", (), g=before[want]), \
        "the graph of the stretch it was minted over held it alone, and goes"


#  WHAT EACH WANT'S ESTIMATE READS IN THE PRESENT GROUND — written by `weigh` on the want's
#  weighing there, off the select the want's `planning:estimates` points at.
_REMAINING_Q = """
SELECT ?for ?left WHERE {
  GRAPH ?cat { ?cat a orexis:CatalogueGraph .
               ?x a planning:Weighing ; planning:for ?for ; planning:weighs ?g ; planning:remaining ?left .
               ?g a planning:GroundGraph } }"""


def test_two_wants_under_one_desire_read_two_estimates(monkeypatch, snapshots):
    """The estimate is the desire's instantiated at the want's instance, as the met-test is: the
    `two_parcels_two_estimates` case derived and each want weighed in the present ground, parcel
    A's want reads three drives and parcel B's two, where the desire's select — `$this` unbound,
    every parcel — reads their sum. Before #893 each want pointed at the desire's select and both
    read five, so a want per parcel paid for the other van's forks."""
    from agent.store import rows
    monkeypatch.setattr(clock, "now", lambda: snapshots.NOW)
    store = snapshots.stand_in(CASES_DIR / "two_parcels_two_estimates.trig")
    lay_ground(store, snapshots.NOW)
    for pair in unweighed(store):
        weigh(store, pair["for"], pair["about"])
    wants = derive_wants(store, snapshots.NOW)
    assert len(wants) == 2, wants
    for want in sorted(wants):
        for pair in unweighed(store, for_=want):
            weigh(store, want, pair["about"])
    left = {r["for"].rsplit(".", 1)[-1]: float(r["left"]) for r in rows(store, _REMAINING_Q, ())}
    assert left == {"parcel_a": 3.0, "parcel_b": 2.0}, left
