"""agora-influx — give each agent a bucket of its own, and a token that opens only it.

  agora-influx society        -> a bucket and a scoped token per agent in world/society

The operator's half of the series store; `influx_writer.py` is the agent's half. They are
separate modules because they are separate privileges: the writer holds one token for one
bucket, this holds the admin token that opens every bucket, and nothing that runs inside an
agent may import this.

**Why per agent.** Before this, one bucket and one admin token were handed to every container,
so `fern` could not read `tomato`'s beliefs but could read its entire moisture history — the
raw state that the band-only disclosure on the bus exists to withhold. Influx 2.x permissions
are per bucket, not per tag, so isolation means a bucket each. See
knowledge/decisions/series-and-bus-isolation.md.

**Why every agent, and not only the ones that observe.** Deciding here which capabilities write
history would put that knowledge in a second place, beside the world that already implies it,
and the two would drift. A bucket nobody writes to grants nobody anything, so uniform is both
simpler and safer than clever.

**Why the name is not in the world.** A topic is a rendezvous — two parties must name the same
string or they never meet — so topics are ratified in `world.ttl`. A bucket has exactly one
writer and nobody to agree with, which makes it deployment, like the store's URL. The agent is
never told the convention: it reads the name out of the credential file mounted for it, so no
process builds a destination from a naming rule.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

from dotenv import dotenv_values
from influxdb_client import Authorization, BucketRetentionRules, InfluxDBClient, Permission, \
    PermissionResource

from . import compose
from agent.config import REPO_ROOT, env
from agent.genesis import world_dir, worlds

log = logging.getLogger("influx")

ADMIN_ENV = REPO_ROOT / "infra" / "secrets" / "admin.env"


class AdminError(RuntimeError):
    """The operator's environment is not set up. Not an agent's problem — nothing is running."""


def bucket_name(world: str, agent_id: str) -> str:
    """The convention, and the only place it is written down.

    Qualified by world because bucket names are org-global: two worlds each holding a `fern`
    would otherwise share one history, and a simulation would write into the record of a real
    plant. A world cannot check this for itself — it is not allowed to know other worlds exist
    — so the convention has to make the collision impossible rather than detectable.
    """
    return f"{world}-{agent_id}"


def credential_file(world: str, agent_id: str) -> Path:
    return world_dir(world) / "secrets" / f"influx-{agent_id}.env"


def _admin_token() -> str:
    """The one credential that opens every bucket, read from its own file.

    Deliberately not from `infra/.env`: that file is handed to every agent container as an
    `env_file`, so anything in it is held by every agent, and scoped tokens would be theatre.
    """
    if not ADMIN_ENV.exists():
        raise AdminError(
            f"{ADMIN_ENV.relative_to(REPO_ROOT)} does not exist — copy infra/admin.env.example "
            "to it and fill it in. It holds the admin token, which no agent may ever hold."
        )
    token = dotenv_values(ADMIN_ENV).get("INFLUX_ADMIN_TOKEN")
    if not token:
        raise AdminError(f"{ADMIN_ENV.relative_to(REPO_ROOT)} declares no INFLUX_ADMIN_TOKEN")
    return token


def _write_credential(path: Path, bucket: str, token: str) -> None:
    """One agent's whole relationship with the series store, in two lines.

    Mounted into that container and no other. `observation.py` reads these two names out of its
    environment exactly as it always did — what changed is not the agent's code but who hands
    it the values.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"# GENERATED by `agora-influx` — this agent's bucket, and a token that opens only it.\n"
        f"# Mounted into agent-{path.stem.removeprefix('influx-')} alone. Never commit.\n"
        f"INFLUX_BUCKET={bucket}\n"
        f"INFLUX_TOKEN={token}\n"
    )
    path.chmod(0o600)


def provision(world: str, rotate: bool = False) -> None:
    """Bring the store into line with the world: a bucket and a scoped token per agent."""
    url = env("INFLUX_URL", "http://localhost:8086")
    org = env("INFLUX_ORG", "agora")
    agents = compose.agent_ids(world)
    if not agents:
        raise SystemExit(f"agora-influx: world {world!r} declares no agents")

    with InfluxDBClient(url=url, token=_admin_token(), org=org) as client:
        organisation = next(
            (o for o in client.organizations_api().find_organizations() if o.name == org), None)
        if organisation is None:
            raise AdminError(
                f"no organization {org!r} at {url} — is `cd infra && podman compose up -d` done?")

        buckets_api = client.buckets_api()
        auth_api = client.authorizations_api()
        existing = {a.description: a for a in auth_api.find_authorizations() or []
                    if a.description}

        for agent_id in agents:
            name = bucket_name(world, agent_id)
            bucket = buckets_api.find_bucket_by_name(name)
            if bucket is None:
                bucket = buckets_api.create_bucket(
                    bucket_name=name, org_id=organisation.id,
                    # Keep everything: the history IS the record, and an agent that forecasts
                    # reads its own past. Retention is an operator's decision, not a default.
                    retention_rules=BucketRetentionRules(type="expire", every_seconds=0))
                log.info("  bucket %-24s created", name)

            path = credential_file(world, agent_id)
            description = f"agora {world}/{agent_id}"
            held = existing.get(description)

            if held and path.exists() and not rotate:
                log.info("  bucket %-24s already granted", name)
                continue
            if held:
                # Influx returns a token's secret only when it is created, so an authorization
                # whose credential file has gone is unrecoverable rather than re-readable. The
                # honest repair is to replace it.
                auth_api.delete_authorization(held)
                log.info("  bucket %-24s token %s", name,
                         "rotated" if rotate else "replaced (credential file was missing)")

            resource = PermissionResource(id=bucket.id, org_id=organisation.id, type="buckets")
            auth = auth_api.create_authorization(authorization=Authorization(
                org_id=organisation.id,
                description=description,
                # read as well as write: an agent that forecasts reads its OWN past. It is the
                # neighbour's past this exists to deny, and the resource id is what denies it.
                permissions=[Permission(action="read", resource=resource),
                             Permission(action="write", resource=resource)]))
            _write_credential(path, name, auth.token)
            if not held:
                log.info("  bucket %-24s granted to agent-%s", name, agent_id)

        _grafana_token(auth_api, organisation, existing, rotate)


GRAFANA_ENV = REPO_ROOT / "infra" / "secrets" / "grafana.env"
GRAFANA_DESC = "agora grafana (read-only, all buckets)"


def _grafana_token(auth_api, organisation, existing, rotate: bool) -> None:
    """The dashboard's own credential: read, every bucket, nothing else.

    Grafana is the one reader that legitimately spans the whole society — it is the operator's
    view, not a member's view of its neighbours — so this is deliberately NOT scoped to one
    bucket. What it does remove is everything else the admin token could do: writing points,
    deleting buckets, and minting further tokens. A dashboard reachable from the network should
    not be able to hand out credentials.

    Org-scoped rather than a list of bucket ids, so a world onboarded tomorrow is visible without
    re-running this. That is the one place where "all buckets" is the right grant.
    """
    held = existing.get(GRAFANA_DESC)
    if held and GRAFANA_ENV.exists() and not rotate:
        log.info("  grafana%-23s already granted", "")
        return
    if held:
        auth_api.delete_authorization(held)

    auth = auth_api.create_authorization(authorization=Authorization(
        org_id=organisation.id,
        description=GRAFANA_DESC,
        permissions=[Permission(action="read",
                                resource=PermissionResource(org_id=organisation.id,
                                                            type="buckets"))]))
    GRAFANA_ENV.parent.mkdir(parents=True, exist_ok=True)
    GRAFANA_ENV.write_text(
        "# GENERATED by `agora-influx` — Grafana's datasource credential.\n"
        "# Read-only across every bucket. NOT the admin token: a dashboard on the network must\n"
        "# not be able to write series or mint credentials.\n"
        f"INFLUX_GRAFANA_TOKEN={auth.token}\n")
    GRAFANA_ENV.chmod(0o600)
    log.info("  grafana%-23s read-only token %s", "", "rotated" if held else "granted")


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    p = argparse.ArgumentParser(
        prog="agora-influx",
        description="Give each of a world's agents its own bucket and a token scoped to it.")
    p.add_argument("world",
                   help="which world. Available: " + ", ".join(worlds()))
    p.add_argument("--rotate", action="store_true",
                   help="replace every token even if one is already held")
    args = p.parse_args()
    log.info("world %s", args.world)
    try:
        provision(args.world, rotate=args.rotate)
    except AdminError as exc:
        raise SystemExit(f"agora-influx: {exc}")


if __name__ == "__main__":
    main()
