"""agora-keygen — create one world's signing keys, once, before it is onboarded.

  agora-keygen society

**Two worlds are two societies and must not be able to sign for each other**, so the pairs belong
to a world rather than to the installation: `world/<name>/secrets/`, never committed.

Since #144/#145 that is more than host and clearing: every agent gets an Ed25519 pair (its own
hand, for presenting claims) and an X25519 pair (its own ear, for vouchers sealed to it), and
the PUBLIC halves are published into `world/<name>/keys.ttl` — generated, gitignored, swept
into the world graph with the ratified files, because a verifier cannot read another agent's
secrets and the world is the one place every member reads.

This is here and not in the runtime for the same reason `agora-influx` is. An agent that could
*mint* a society's keys could sign for that society — it could authorise a match it never won and
validate its own voucher. An actuator holds the two keys it is given, mounted into its container
alone, and can do nothing else with them; `agent.signing` therefore keeps `load_private`, `sign`
and `verify`, and creating a keypair happens here.

The keys sign an actuation command jointly: the host authorises the match and clearing validates
it, and the firmware refuses a command missing either. See knowledge/domain/clearing.md.

See knowledge/domain/onboarding.md.
"""

from __future__ import annotations

import argparse
import os

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey

from agent import genesis, ratified, signing


def create_keypair(name: str) -> None:
    """Write `<name>.key` and `<name>.pub` into the current world's secrets directory.

    PEM/PKCS8, because `agent.signing.load_private` reads it back that way — the format is a
    contract between the two halves and is not this tool's to choose alone.

    Note it OVERWRITES. Regenerating a world's keys invalidates every signature made with the old
    pair, including any voucher a device still holds. That is a seam, not a feature.
    """
    signing.KEYS_DIR().mkdir(parents=True, exist_ok=True)
    key = Ed25519PrivateKey.generate()
    signing.priv_path(name).write_bytes(
        key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
    )
    signing.pub_path(name).write_bytes(
        key.public_key().public_bytes(
            serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
        )
    )


def create_sealing_keypair(name: str) -> None:
    """The X25519 pair beside the Ed25519 one: same PEM contract, different operation.

    Ed25519 signs and does not encrypt — sealing a voucher to its winner (#145) needs its own
    curve operation, so an agent's identity is TWO pairs, minted together.
    """
    signing.KEYS_DIR().mkdir(parents=True, exist_ok=True)
    key = X25519PrivateKey.generate()
    signing.seal_priv_path(name).write_bytes(
        key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
    )


_ROSTER_Q = """SELECT ?a ?id WHERE {
  ?a a <http://example.org/agora#Agent> ; <http://example.org/agora#localId> ?id }"""


def roster(world: str) -> list[tuple[str, str]]:
    """(agent IRI, localId) pairs, from the ratified files.

    The IRI travels with the id because keys.ttl must state keys against each agent's REAL
    node, and an IRI built from the id by convention is exactly the guess rule 1 forbids —
    `ag:supplier` has no `_agent` suffix, and the roster that assumed one attested keys for a
    node that does not exist.
    """
    return sorted({(r["a"], r["id"]) for r in ratified.rows(ratified.dataset(world), _ROSTER_Q)})


def publish_roster(world: str, ids: list[str]) -> None:
    """Write the PUBLIC halves into `world/<name>/keys.ttl`, where `world_files` sweeps it.

    Generated and gitignored like the secrets it mirrors, but public in CONTENT: base64 raw
    keys, nothing a verifier could not be shown. In the world because the world is the one
    thing every member reads — a host verifying a presentation cannot read the presenter's
    secrets, so the roster is how identity is attested (#144, #145). Stated against each
    agent's own node by its known IRI shape, so the graph rather than a lookup table is what
    a verifier reads.
    """
    lines = [
        "@prefix ag: <http://example.org/agora#> .",
        "",
        "# GENERATED by agora-keygen — the public halves of each agent's identity keys",
        "# (#144 signing, #145 sealing). Regenerated with the keys; never edited by hand.",
    ]
    for iri, agent_id in ids:
        sign_b64 = signing.raw_public_b64(signing.load_private(agent_id).public_key())
        seal_b64 = signing.raw_public_b64(signing.load_sealing_private(agent_id).public_key())
        lines.append(f'<{iri}> ag:signingKey "{sign_b64}" ; ag:sealingKey "{seal_b64}" .')
    (genesis.world_dir(world) / "keys.ttl").write_text("\n".join(lines) + "\n")


def main() -> None:
    p = argparse.ArgumentParser(
        prog="agora-keygen",
        description="Create one world's signing keys. Two worlds are two societies and must "
                    "not be able to sign for each other.",
    )
    p.add_argument("world",
                   help="which world. Available: " + ", ".join(genesis.worlds()))
    world = p.parse_args().world
    os.environ["AGORA_WORLD"] = world
    for name in ("host", "clearing"):
        create_keypair(name)
    # Every agent's identity, beside the society's own (#144, #145). The roster of public
    # halves lands in the world, where every member reads it.
    ids = roster(world)
    for _, agent_id in ids:
        create_keypair(agent_id)
        create_sealing_keypair(agent_id)
    publish_roster(world, ids)
    print(f"created {signing.KEYS_DIR()}/[host|clearing|agent].key pairs and keys.ttl "
          f"for {len(ids)} agents")


if __name__ == "__main__":
    main()
