"""Generate the store's access control from the world — the ACL is derived, like everything else.

Who exists, and therefore who needs a credential and which graphs they may read, is stated in
`genesis/world.ttl`. Hand-maintaining a second list in a Fuseki config would be exactly the
drift this architecture removes, so the config is generated:

  agora-acl [world]   writes infra/fuseki/config.ttl and keys/fuseki/*

The ACL follows whichever world you seeded — a credential per agent that world declares — so
re-run it after `agora-seed <name>` with the same name.

Two doors over one store, because Jena's data access control is **read-only**:

  /ds/sparql     secured. Each agent authenticates as itself and can read the world, the
                 ontology, the sensed graph, and its OWN beliefs. Another agent's beliefs
                 come back empty — not as an error, as absence.
  /ds-rw         the plain store. `update` is open to every agent (each writes its own
                 readings), `data` and `sparql` are admin-only, for seeding and validation.

What this does and does not buy: **reads are enforced**, so privacy stops being a convention.
Writes are not graph-scoped — Jena cannot do that — so an agent could in principle write into
another's graph. That is the same integrity-of-self-report assumption trusted-agent mode
already accepts (see knowledge/decisions/trusted-agent-mode.md); the gap that was open was
*reading*, and this closes it.

See knowledge/decisions/belief-base-isolation.md.
"""

from __future__ import annotations

import logging
import secrets
from pathlib import Path

import rdflib

from .config import PROJECT_ROOT
from .ontology import AG, ONTOLOGY_GRAPH, SENSED_GRAPH, WORLD_GRAPH, beliefs_graph
from .seed import DEFAULT_WORLD, world_dir, worlds

log = logging.getLogger("acl")

REPO_ROOT = PROJECT_ROOT.parent
CONFIG_OUT = REPO_ROOT / "infra" / "fuseki" / "config.ttl"
SECRETS_DIR = REPO_ROOT / "keys" / "fuseki"  # gitignored, like the signing keys

# Everything an agent may read besides its own beliefs. All public by design.
SHARED_GRAPHS = (ONTOLOGY_GRAPH, WORLD_GRAPH, SENSED_GRAPH)


def agent_ids(world: str = DEFAULT_WORLD) -> list[str]:
    """Who exists, according to the world itself."""
    g = rdflib.Graph().parse(world_dir(world) / "world.ttl", format="turtle")
    q = f"SELECT ?id WHERE {{ ?a a <{AG}Agent> ; <{AG}localId> ?id }}"
    return sorted({str(row.id) for row in g.query(q)})


def read_or_make_secret(agent_id: str, secrets_dir: Path = SECRETS_DIR) -> str:
    """One credential per agent, kept next to the signing keys and never committed.

    Stable across regeneration: rotating every agent's password because a new plant was
    added would be a needless outage.
    """
    secrets_dir.mkdir(parents=True, exist_ok=True)
    path = secrets_dir / f"{agent_id}.pw"
    if path.exists():
        return path.read_text().strip()
    secret = secrets.token_urlsafe(24)
    path.write_text(secret + "\n")
    path.chmod(0o600)
    return secret


def build_config(ids: list[str], passwd_path: str, tdb_location: str) -> str:
    """The Fuseki assembler: a secured read door and a plain write door over one store."""
    entries = "\n".join(
        f'    access:entry [ access:user "{a}" ; access:graphs (\n'
        + "".join(f"        <{g}>\n" for g in (*SHARED_GRAPHS, beliefs_graph(a)))
        + "    ) ] ;"
        for a in ids
    ).rstrip(";") + "."

    updaters = " ".join(f'"{a}"' for a in ("admin", *ids))
    return f"""# GENERATED by `agora-acl` from genesis/world.ttl — do not edit by hand.
#
# Who may read what is derived from who exists in the world, so the two cannot drift apart.
# Regenerate after any change to the agents in genesis/world.ttl.
#
# Two doors over ONE store, because Jena's access control is read-only:
#   /ds     secured  — an agent sees the shared graphs and its own beliefs, nothing else
#   /ds-rw  plain    — update for every agent (its own readings), read/GSP for admin only
#
# See knowledge/decisions/belief-base-isolation.md.

@prefix fuseki:  <http://jena.apache.org/fuseki#> .
@prefix ja:      <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix access:  <http://jena.apache.org/access#> .
@prefix tdb2:    <http://jena.apache.org/2016/tdb#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix :        <#> .

[] rdf:type fuseki:Server ;
   fuseki:passwd "{passwd_path}" ;
   fuseki:services ( <#secured> <#plain> ) .

<#secured> rdf:type fuseki:Service ;
    fuseki:name "ds" ;
    fuseki:endpoint [ fuseki:operation fuseki:query ; fuseki:name "sparql" ] ;
    fuseki:dataset <#access> .

<#plain> rdf:type fuseki:Service ;
    fuseki:name "ds-rw" ;
    fuseki:endpoint [ fuseki:operation fuseki:update ; fuseki:name "update" ;
                      fuseki:allowedUsers ( {updaters} ) ] ;
    fuseki:endpoint [ fuseki:operation fuseki:gsp-rw ; fuseki:name "data" ;
                      fuseki:allowedUsers ( "admin" ) ] ;
    fuseki:endpoint [ fuseki:operation fuseki:query ; fuseki:name "sparql" ;
                      fuseki:allowedUsers ( "admin" ) ] ;
    fuseki:dataset <#store> .

<#access> rdf:type access:AccessControlledDataset ;
    access:registry <#registry> ;
    access:dataset  <#store> .

<#store> rdf:type tdb2:DatasetTDB2 ;
    tdb2:location "{tdb_location}" .

<#registry> rdf:type access:SecurityRegistry ;
{entries}
"""


def generate(admin_password: str = "admin", world: str = DEFAULT_WORLD) -> None:
    ids = agent_ids(world)
    if not ids:
        raise SystemExit(f"no agents in world {world!r} — nothing to authorise")

    lines = [f"admin={admin_password}"]
    for agent_id in ids:
        lines.append(f"{agent_id}={read_or_make_secret(agent_id)}")
    passwd = SECRETS_DIR / "passwd"
    passwd.write_text("\n".join(lines) + "\n")
    passwd.chmod(0o600)

    CONFIG_OUT.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_OUT.write_text(build_config(ids, "/fuseki-secrets/passwd", "/fuseki-data/tdb2"))

    log.info("authorised %d agent(s) of world %r: %s", len(ids), world, ", ".join(ids))
    log.info("  config      -> %s", CONFIG_OUT)
    log.info("  credentials -> %s/  (gitignored; each agent reads its own)", SECRETS_DIR)


def main() -> None:
    import argparse
    import os

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    p = argparse.ArgumentParser(
        prog="agora-acl",
        description="Generate the store's access control from a ratified world.",
    )
    p.add_argument("world", nargs="?", default=DEFAULT_WORLD,
                   help=f"which world (default: {DEFAULT_WORLD}). Available: "
                        + ", ".join(worlds()))
    generate(os.environ.get("FUSEKI_PASSWORD", "admin"), p.parse_args().world)


if __name__ == "__main__":
    main()
