// Agora — ESP32 soil-moisture SENTINEL (sensing:PushProcedure + sensing:CrossingProcedure).
//
// The second firmware, and the inverse temperament of the first. The moisture-sensor node is
// governed: the agent commands its cadence and its band, and the board keeps them. A sentinel
// is autonomous: it takes NO orders — no command topic, no subscribe, nothing to parse — so
// its agent derives sensing:Listening and can only receive. What it does instead:
//
//   - the ULP watches a band COMPILED IN from the world's own operating range, sampling the
//     probe about once a second for microamps while everything else deep-sleeps;
//   - a crossing wakes the radio and publishes, marked "wake":"crossing" — the world changed,
//     so the world says so, within a second rather than a polling window;
//   - a slow HEARTBEAT wake publishes regardless, so silence stays distinguishable from death:
//     the agent's Listening freshness rule (sensing:maxReadingAgeS) is an absolute, and the
//     heartbeat is generated to fit under it.
//
// Sampling is not reporting: the per-second looks die in a register — no observation, no
// testimony — and only a crossing or a heartbeat becomes a published reading.
//
//   publish:   MOISTURE_TOPIC   {"value":0.183,"sensor":"<SENSOR_ID>"}          heartbeat
//              MOISTURE_TOPIC   {"value":0.391,"sensor":"<SENSOR_ID>",
//                                "wake":"crossing"}                             the news
//
// No sleep_s in the payload, deliberately: the ack is a receipt for a commanded cadence, and
// nothing commands this board. A push device that acked would invite its agent to hold a
// freshness rule the vocabulary says it may not have — the same reason the simulator's push
// mode omits it.
//
// COMPILE-UNTESTED HERE, like all firmware: the bench has the last word.

#include <Arduino.h>
#include <WiFi.h>
#include <PubSubClient.h>
#include <esp_sleep.h>

#include "config.h"

// The watch lives in ulp_watch.cpp; the band it loads is WAKE_BAND_LOW/HIGH from config.h —
// the world's operating range for this pot, generated by agora-firmware — and the derivation
// of its one-second internal cadence from the worst credible slew is written there.
#include "ulp_watch.h"

#ifndef HEARTBEAT_S
#define HEARTBEAT_S 600         // generated from the polling agent's own freshness rule
#endif
#ifndef MQTT_TRIES
#define MQTT_TRIES 10
#endif
#ifndef WIFI_TIMEOUT_MS
#define WIFI_TIMEOUT_MS 20000
#endif

WiFiClient wifi;
PubSubClient mqtt(wifi);

static float lastFrac = 0.0f;
static float lastRaw = 0.0f;

static float readMoisture() {
  const int samples = 16;
  long sum = 0;
  for (int i = 0; i < samples; i++) {
    sum += analogRead(MOISTURE_PIN);
    delay(5);
  }
  lastRaw = sum / (float)samples;
  float frac = (ADC_DRY - lastRaw) / (float)(ADC_DRY - ADC_WET);
  if (frac < 0.0f) frac = 0.0f;
  if (frac > 1.0f) frac = 1.0f;
  return frac;
}

static bool connectWifi() {
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  uint32_t began = millis();
  while (WiFi.status() != WL_CONNECTED) {
    if (millis() - began > WIFI_TIMEOUT_MS) {
      Serial.printf("no wifi after %ums\n", millis() - began);
      return false;
    }
    delay(300);
  }
  return true;
}

static bool connectMqtt() {
  String clientId = String("agora-sentinel-") + SENSOR_ID + "-"
                    + String((uint32_t)ESP.getEfuseMac(), HEX);
  for (unsigned attempt = 1; attempt <= MQTT_TRIES; attempt++) {
    if (mqtt.connect(clientId.c_str(), MQTT_USER, MQTT_PASS)) return true;
    Serial.printf("MQTT attempt %u failed (state %d)\n", attempt, mqtt.state());
    delay(1000);
  }
  return false;
}

void setup() {
  Serial.begin(115200);
  delay(200);
  analogReadResolution(12);

  bool crossing = wokeByCrossing();
  lastFrac = readMoisture();
  Serial.printf("\nagora moisture sentinel  %s\nmoisture %.3f  [raw %.0f]  wake: %s\n",
                SENSOR_ID, lastFrac, lastRaw, crossing ? "crossing" : "heartbeat");

  if (connectWifi()) {
    mqtt.setServer(MQTT_HOST, MQTT_PORT);
    if (connectMqtt()) {
      char payload[128];
      if (crossing) {
        snprintf(payload, sizeof(payload),
                 "{\"value\":%.3f,\"sensor\":\"%s\",\"wake\":\"crossing\"}",
                 lastFrac, SENSOR_ID);
      } else {
        snprintf(payload, sizeof(payload), "{\"value\":%.3f,\"sensor\":\"%s\"}",
                 lastFrac, SENSOR_ID);
      }
      bool sent = mqtt.publish(MOISTURE_TOPIC, payload);
      Serial.printf("%s %s   %s\n", MOISTURE_TOPIC, payload, sent ? "sent" : "REFUSED");
      mqtt.disconnect();
    }
  }

  // Watch, then sleep until the band breaks or the heartbeat comes due — whichever first.
  delay(50);
  armUlpWatch();
  esp_sleep_enable_timer_wakeup((uint64_t)HEARTBEAT_S * 1000000ULL);
  esp_deep_sleep_start();
}

void loop() {}  // never reached — deep sleep restarts from setup()
